"""
Smart Home Energy Monitoring System - Alert Logger.

This module is responsible for persisting alert events generated by the
Alert Engine into a CSV file for historical analysis and auditing.

Responsibilities:
-----------------
- Store alert events
- Maintain alert history
- Provide chronological alert records
- Support troubleshooting and diagnostics

Output:
-------
outputs/alerts/alert_log.csv

Author: Akash Das
Project: Smart Home Energy Monitoring System
"""

from pathlib import Path
from datetime import datetime
import csv

from simulator.core.config import (
    ALERTS_DIR
)


class AlertLogger:
    """
    CSV-based alert logger.
    """

    def __init__(self):
        """
        Initialize alert log file.
        """

        self.file_path = (
            ALERTS_DIR /
            "alert_log.csv"
        )

        self._initialize_file()

    # ======================================================
    # FILE INITIALIZATION
    # ======================================================

    def _initialize_file(self):
        """
        Create CSV file with headers if it does not exist.
        """

        if not self.file_path.exists():

            with open(
                self.file_path,
                mode="w",
                newline="",
                encoding="utf-8"
            ) as file:

                writer = csv.writer(file)

                writer.writerow([
                    "timestamp",
                    "appliance",
                    "power_w",
                    "energy_kwh",
                    "alert_count",
                    "status"
                ])

    # ======================================================
    # ALERT LOGGING
    # ======================================================

    def log_alert(
        self,
        appliance,
        power_w,
        energy_kwh,
        alert_count,
        status
    ):
        """
        Append alert event to CSV file.
        """

        with open(
            self.file_path,
            mode="a",
            newline="",
            encoding="utf-8"
        ) as file:

            writer = csv.writer(file)

            writer.writerow([
                datetime.now().isoformat(),
                appliance,
                round(power_w, 2),
                round(energy_kwh, 6),
                alert_count,
                status
            ])