"""
Smart Home Energy Monitoring System - Analytics Package.

This package contains all mathematical and analytical components used to
process electrical telemetry generated by the simulator or received from
physical IoT devices.

The analytics layer transforms raw voltage and current measurements into
meaningful energy metrics that can be visualized, reported, and used for
decision-making.

Core Responsibilities:
- Power calculations
- Energy consumption calculations
- Cost estimation
- Electrical metric derivation
- Consumption analytics

Modules:
- power_calculator.py
    Calculates:
    * Apparent Power (VA)
    * Active Power (W)
    * Reactive Power (VAR)
    * Power Factor Metrics

- energy_calculator.py
    Calculates:
    * Energy Consumption (Wh)
    * Energy Consumption (kWh)
    * Rolling Energy Totals
    * Daily and Monthly Usage

- cost_calculator.py
    Calculates:
    * Estimated Electricity Costs
    * Tariff-Based Billing
    * Daily Cost Projections
    * Monthly Cost Projections

Key Formula Categories:
- Apparent Power:
    S = V × I

- Active Power:
    P = V × I × PF

- Reactive Power:
    Q = √(S² - P²)

- Energy:
    E = P × t

- Cost:
    Cost = Energy × Tariff

Design Goals:
- Mathematical accuracy
- Reusability
- Modular architecture
- Hardware-independent operation
- Unit-test-friendly implementation

This package contains pure analytical logic and intentionally avoids
dependencies on MQTT, reporting, dashboarding, or hardware interfaces.

Author: Akash Das
Project: Smart Home Energy Monitoring System
"""

__all__ = [
    "power_calculator",
    "energy_calculator",
    "cost_calculator"
]